export const titles = [
    // Expense Categories
    "groceries",
    "supermarket",
    "organic store",
    "farmer's market",
    "dining",
    "restaurant",
    "fast food",
    "coffee shop",
    "food",
    "bus",
    "car",
    "traveling",
    "truck",
    "tracter",
    "bakery",
    "butcher",
    "fish market",
    "deli",
    "convenience store",
    "meal delivery",
    "meal kit service",
    "snacks",
    "beverages",
    "rental income",
    "takeout",
    "catering",
    "specialty foods",
    "shopping",
    "clothing",
    "electronics",
    "furniture",
    "home decor",
    "jewelry",
    "accessories",
    "shoes",
    "bags",
    "cosmetics",
    "personal care products",
    "toiletries",
    "books",
    "stationery",
    "gifts",
    "household items",
    "kitchenware",
    "bedding",
    "appliances",
    "DIY supplies",
    "craft supplies",
    "toys",
    "sports gear",
    "outdoor equipment",
    "seasonal decorations",
    "entertainment",
    "movies",
    "concerts",
    "sports events",
    "video games",
    "theater",
    "museums",
    "amusement parks",
    "zoos",
    "escape rooms",
    "art classes",
    "dance classes",
    "music lessons",
    "cultural events",
    "festivals",
    "book clubs",
    "hobbies",
    "crafts",
    "gaming consoles",
    "board games",
    "puzzles",
    "rent",
    "apartment",
    "office space",
    "storage",
    "mortgage",
    "property tax",
    "home insurance",
    "utilities",
    "electricity",
    "water",
    "gas",
    "internet",
    "phone",
    "home maintenance",
    "home repairs",
    "property management fees",
    "pest control",
    "landscaping",
    "snow removal",
    "pool maintenance",
    "security system",
    "lawn care",
    "housekeeping",
    "cleaning supplies",
    "household repairs",
    "furniture rental",
    "moving expenses",
    "transport",
    "public transport",
    "fuel",
    "car maintenance",
    "taxi",
    "rideshare",
    "car rental",
    "vehicle insurance",
    "parking fees",
    "tolls",
    "roadside assistance",
    "vehicle registration",
    "auto repairs",
    "vehicle cleaning",
    "carwash",
    "bike maintenance",
    "train tickets",
    "bus tickets",
    "plane tickets",
    "boat tickets",
    "transportation subscriptions",
    "car lease",
    "healthcare",
    "doctor",
    "pharmacy",
    "hospital",
    "dental",
    "vision care",
    "prescriptions",
    "medical supplies",
    "physical therapy",
    "mental health services",
    "emergency care",
    "wellness checks",
    "preventive care",
    "vaccinations",
    "urgent care",
    "specialist consultations",
    "laboratory tests",
    "medical equipment",
    "home health care",
    "alternative medicine",
    "health insurance",
    "education",
    "tuition",
    "courses",
    "books",
    "school supplies",
    "online classes",
    "workshops",
    "seminars",
    "training programs",
    "certifications",
    "college fees",
    "university fees",
    "study materials",
    "lab fees",
    "extracurricular activities",
    "tutoring",
    "test preparation",
    "student loans",
    "education insurance",
    "education software",
    "language classes",
    "adult education",
    "personal care",
    "haircuts",
    "spa",
    "gym",
    "salon",
    "massage therapy",
    "nail care",
    "skincare products",
    "hair care products",
    "cosmetic surgery",
    "personal grooming",
    "fitness classes",
    "meditation classes",
    "wellness programs",
    "self-care products",
    "therapy sessions",
    "personal training",
    "dietary supplements",
    "beauty treatments",
    "personal hygiene items",
    "toiletries",
    "charity",
    "donations",
    "fundraisers",
    "home improvement",
    "gardening",
    "pet care",
    "baby supplies",
    "sports equipment",
    "hobbies",
    "crafts",
    "seasonal items",
    "gifts",
    "party expenses",
    "medical supplies",
    "legal fees",
    "bank fees",
    "clothing alterations",
    "dry cleaning",
    "laundry",
    "home security",
    "pest control",
    "household supplies",
    "property management",
    "subscriptions",
    "seasonal decorations",
    "event tickets",
    "professional memberships",
    "yoga classes",
    "housekeeping services",
    "appliance repair",
    "childcare",
    "elder care",
    "emergency expenses",
    "funeral expenses",
    "legal settlements",
    "credit card fees",
    "grocery delivery",
    "home office supplies",
  
    // Income Categories
    "teaching",
    "stock",
    "bid",
    "sell bike",
    "bike sell",
    "bike",
    "salary",
    "monthly salary",
    "biweekly salary",
    "weekly salary",
    "hourly wage",
    "overtime",
    "bonus",
    "commission",
    "tips",
    "allowances",
    "performance bonuses",
    "holiday bonuses",
    "severance pay",
    "sick leave pay",
    "vacation pay",
    "profit sharing",
    "equity compensation",
    "investment",
    "stocks",
    "mutual funds",
    "bonds",
    "real estate investments",
    "index funds",
    "ETFs",
    "commodities",
    "cryptocurrency",
    "dividends",
    "interest income",
    "capital gains",
    "royalties",
    "REITs",
    "venture capital",
    "angel investing",
    "crowdfunding returns",
    "peer-to-peer lending",
    "treasury bills",
    "certificate of deposits",
    "freelance",
    "consulting",
    "project work",
    "contract work",
    "gigs",
    "side business",
    "remote work",
    "service contracts",
    "consulting fees",
    "retainer fees",
    "writing fees",
    "design fees",
    "development fees",
    "photography fees",
    "event planning fees",
    "coaching fees",
    "speaking engagements",
    "training workshops",
    "project commissions",
    "rental income",
    "real estate rental",
    "vacation rental",
    "property management",
    "royalties",
    "book royalties",
    "music royalties",
    "patent royalties",
    "licensing fees",
    "art royalties",
    "film royalties",
    "software royalties",
    "franchise fees",
    "advertising royalties",
    "intellectual property income",
    "commercial leases",
    "land leases",
    "gift",
    "family gifts",
    "friends gifts",
    "inheritance",
    "grants",
    "scholarships",
    "donations",
    "crowdfunding",
    "rebates",
    "cashback",
    "refunds",
    "prizes",
    "winnings",
    "lottery winnings",
    "contest prizes",
    "settlements",
    "compensations",
    "side income",
    "affiliate income",
    "residual income",
    "network marketing",
    "pension",
    "annuity",
    "social security",
    "unemployment benefits",
    "disability benefits",
    "military benefits",
    "child support",
    "alimony",
    "insurance payouts",
    "legal settlements",
    "loan repayments",
    "cash gifts",
    "royalty income",
    "reimbursements",
    "cash advances",
    "sale of assets",
    "eBay sales",
    "Etsy sales",
    "auction sales",
    "online marketplace sales",
    "freelance gigs",
    "consulting contracts",
    "project fees",
    "investment returns",
    "commission income",
    "dividends",
    "interest from savings",
    "interest from investments"
  ];
  